### PR TITLE
Patching element.constructor sub-object

### PR DESCRIPTION
**Pull request by mauricioszabo**
Fixes some issues with some Pulsar packages

### CODE REVIEW

**Comment by confused-Techie** [comment]
Do you think it's a good idea to first get tests setup on this repo? Or do you want to just get this one merged, then consider it later?

**Comment by mauricioszabo** [comment]
@confused-Techie not really - this is a hack of a hack to make packages still work. I see no gain for us to even _keep_ these tests, honestly...

**Comment by confused-Techie** [comment]
@mauricioszabo Ahh I see, so in that case, since I'm pretty sure we are already using this commit in production, lets go ahead and merge this one. Is that right that this is the commit currently being used within Pulsar?

**Comment by mauricioszabo** [comment]
Yes, this is the one we're already using. I completely forgot about that too :D

**Pull request merged**
